version: "3.8"
   
services:
  nginx-ugc:
    image: nginx:1.21-alpine
    container_name: nginx-ugc
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - event-api
    networks:
      - web-service

  event-api:
    build:
      context: .
      dockerfile: Dockerfile.api.yc.dev
    container_name: event-api
    ports:
      - "8080:8080"
    volumes:
      - ./src/app:/usr/src/app
    env_file:
      - ./.env
    networks:
      - backend_network
      - web-service
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - backend_network

networks:
  backend_network:
  web-service:
