# Generated by Django 3.2 on 2022-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='subscription_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='флаг необходимости наличия подписки'),
        ),
    ]
